FROM ollama/ollama

VOLUME /root/.ollama

RUN apt-get update --fix-missing && apt-get install -y --fix-missing curl

# smallest at the moment
ARG OLLAMA_MODEL="gemma3:1b" 

ENV OLLAMA_MODEL_NAME=${OLLAMA_MODEL}

# run server to pull the selected model
RUN ollama serve & \
    OLLAMA_PID=$! && \
    sleep 5 && \
    ollama pull ${OLLAMA_MODEL_NAME} && \
    kill $OLLAMA_PID

EXPOSE 11434

ENTRYPOINT ["ollama", "serve"]